kind: pipeline
type: docker
name: production

platform:
  arch: amd64
  os: linux

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: steverobertson/domaindriven
      tags: ["latest"]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - main

---
kind: pipeline
type: docker
name: development

platform:
  arch: amd64
  os: linux

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: steverobertson/domaindriven_dev
      tags: ["latest"]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - dev
