table:
  name: space
  schema: public
object_relationships:
  - name: updated_space
    using:
      foreign_key_constraint_on:
        column: space_id
        table:
          name: updated_space
          schema: public
array_relationships:
  - name: model_backups
    using:
      foreign_key_constraint_on:
        column: space_id
        table:
          name: backup
          schema: public
  - name: models
    using:
      foreign_key_constraint_on:
        column: space_id
        table:
          name: model
          schema: public
  - name: user_spaces
    using:
      foreign_key_constraint_on:
        column: space_id
        table:
          name: user_space
          schema: public
  - name: users
    using:
      foreign_key_constraint_on:
        column: personal_space_id
        table:
          name: user
          schema: public
insert_permissions:
  - role: domaindriven-admin
    permission:
      check: {}
      columns:
        - info
        - name
select_permissions:
  - role: domaindriven-user
    permission:
      columns:
        - created_at
        - info
        - name
        - space_id
      filter:
        user_spaces:
          user_id:
            _eq: X-Hasura-User-Id
update_permissions:
  - role: domaindriven-admin
    permission:
      columns:
        - info
        - name
      filter: {}
      check: null
delete_permissions:
  - role: domaindriven-admin
    permission:
      filter: {}
event_triggers:
  - name: new_space
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: DD_EVENT_CALLBACK_NEW_SPACE
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
