table:
  name: context
  schema: public
object_relationships:
  - name: model
    using:
      foreign_key_constraint_on: model_id
array_relationships:
  - name: connections
    using:
      foreign_key_constraint_on:
        column: from_context_id
        table:
          name: connection
          schema: public
  - name: connectionsByToContextId
    using:
      foreign_key_constraint_on:
        column: to_context_id
        table:
          name: connection
          schema: public
  - name: demoteds
    using:
      foreign_key_constraint_on:
        column: context_id
        table:
          name: demoted
          schema: public
  - name: groups
    using:
      foreign_key_constraint_on:
        column: context_id
        table:
          name: group
          schema: public
  - name: relations
    using:
      foreign_key_constraint_on:
        column: context_id
        table:
          name: relation
          schema: public
  - name: terms
    using:
      foreign_key_constraint_on:
        column: context_id
        table:
          name: term
          schema: public
insert_permissions:
  - role: domaindriven-user
    permission:
      check:
        model:
          space:
            user_spaces:
              user_id:
                _eq: X-Hasura-User-Id
      columns:
        - model_id
        - name
        - notes
select_permissions:
  - role: domaindriven-user
    permission:
      columns:
        - context_id
        - name
        - created_at
        - model_id
        - notes
      filter:
        model:
          space:
            user_spaces:
              user_id:
                _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: domaindriven-user
    permission:
      columns:
        - name
        - notes
      filter:
        model:
          space:
            user_spaces:
              user_id:
                _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: domaindriven-user
    permission:
      filter:
        model:
          space:
            user_spaces:
              user_id:
                _eq: X-Hasura-User-Id
event_triggers:
  - name: context_changed
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: DD_EVENT_CALLBACK_MODEL_CHANGED
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
